### ISSUE TITLE
Merge repository

### ISSUE THREAD

**Issue by scolladon** [rsoesemann/apex-chainable-batch#1]
Hi Robert,

Do you think we should merge our repository ? https://github.com/scolladon/apex-chainable
We had a very similar approach !

I am available to discuss with you !

- Current choices,
- Challenges faced
- Next feature to add

Seb

**Comment by rsoesemann** [comment]
Hi I see no reasons to merge two libs just because of similar base ideas. Who would benefit from that. Besides that I think your code looks more more complicated. Less lean and clean... Feel free to open a fork with a merge and pr it.

**Comment by scolladon** [comment]
I see your point.

Thanks for the encouragement to collaborate on this project.
If you have time, I'll be happy to hear what you would do to improve the code of apex-chainable.
I'm available on [gitter](https://gitter.im/scolladon)

Cheers
